name: Tests

on: [push, pull_request]

jobs:
   test:
      runs-on: ubuntu-latest

      defaults:
         run:
            working-directory: ./frontend

      steps:
         - name: Checkout
           uses: actions/checkout@v4

         - name: Setup Bun
           uses: oven-sh/setup-bun@v1

         - name: Install dependencies
           run: bun install

         - name: Run tests
           run: bunx vitest --config vitest.config.ts
